<a href="https://colab.research.google.com/github/MIAPTA/Challenge-DScience/blob/main/Copia_de_numpy_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [ ]:
import numpy as np
array = np.array ([7, 8, 4, 5, 1, 2])

Using slicing print the elements from index 3 to the end of the array.



In [ ]:
print (array[3:])

[5 1 2]


Using slicing print all the elements except the last one.



In [ ]:
print (array[:-1])

[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [ ]:
print(array[1:5])

[8 4 5 1]


Reshape the array into a 3 rows and 2 cols (3,2).



In [ ]:
arr = array.reshape(3,2)
print (arr)

[[7 8]
 [4 5]
 [1 2]]


Print all the array elements one by one (iterating).



In [ ]:
for ar in array:
  print (ar)


7
8
4
5
1
2


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [ ]:
ndarray = np.array([0, 6, 9], dtype='O')

print(ndarray)
print(ndarray.dtype)

[0 6 9]
object


Join the two arrays.



In [ ]:
jarray = np.concatenate((array, ndarray))
print (jarray)

[7 8 4 5 1 2 0 6 9]


Using filtering print only the odd numbers of the joined array.



In [ ]:
filter_odd = []
for element in jarray:
  if element % 2 == 1:
    filter_odd.append(True)
  else:
    filter_odd.append(False)
oddar = jarray[filter_odd]
print (oddar)

[7 5 1 9]


Sort the joined array elements.



In [ ]:
print(np.sort(jarray))

[0 1 2 4 5 6 7 8 9]


Store in an array the names of the months.



In [ ]:
marray = np.array(['january', 'february', 'march', 'april', 'may', 'juny', 'july', 'august', 'september', 'october', 'november', 'december'])
print (marray)

['january' 'february' 'march' 'april' 'may' 'juny' 'july' 'august'
 'september' 'october' 'november' 'december']


Split the months array in 4 periods of 3 elements each one.



In [ ]:
sarr = np.array_split(marray, 4)
print (sarr)

[array(['january', 'february', 'march'], dtype='<U9'), array(['april', 'may', 'juny'], dtype='<U9'), array(['july', 'august', 'september'], dtype='<U9'), array(['october', 'november', 'december'], dtype='<U9')]


Create an array with genre information ['F','M','F','F','M','F'].



In [ ]:
garr = np.array(['F','M', 'F', 'F', 'M', 'F'])
print (garr)

['F' 'M' 'F' 'F' 'M' 'F']


Find the indexes where the value is F.



In [ ]:
x = np.where(garr == 'F')
print (x)

(array([0, 2, 3, 5]),)


Store in an array the age information [18,20,19,23,19,20].



In [ ]:
arrg = np.array([18,20,19,23,19,20])
print (arrg)

[18 20 19 23 19 20]


Create a filter array with values < 20.



In [ ]:
filter_arr = []
for element in arrg:
  if element < 20:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
agearr = arrg[filter_arr]
print (agearr)

[18 19 19]


Change the 3 index element with a value of 22



In [ ]:
arrg[3] = 22
print (arrg)

[18 20 19 22 19 20]


Print the 4 index element.

In [ ]:
print (arrg[4])

19
